### PR TITLE
Update bcwc_pcie-9999.ebuild to use master 

### PR DESCRIPTION
**Pull request by cjosephson**
See  and https://github.com/toaster/gentoo-overlay/issues/12 and https://github.com/patjak/bcwc_pcie/issues/197

### CODE REVIEW

**Comment by toaster** [comment]
Thank you very much for the update. Unfortunately I have no hardware to test this ATM. I will merge it without trying it out :).

**Comment by simonvanderveldt** [comment]
FYI Portage isn't happy after these changes
```
Calculating dependencies | * Digest verification failed:
 * /usr/local/portage/toaster/media-video/bcwc_pcie/bcwc_pcie-9999.ebuild
 * Reason: Filesize does not match recorded size
 * Got: 773
 * Expected: 754
```

**Comment by cjosephson** [comment]
@simonvanderveldt I forgot to update the manifest after adding an additional v4l dependency (the driver compiles without v4l, but the video doesn't work until that dependency is added)

Doing another pull request in a moment, but in the meantime it is a very simple fix:

`cd /var/lib/layman/toaster/media-video/bcwc_pcie && sudo ebuild bcwc_pcie-9999.ebuild manifest`

**Comment by simonvanderveldt** [comment]
That's correct :)

@toaster FYI: you can enable thin-manifests so there's no need to update the manifest for changes to files within the repo. See https://wiki.gentoo.org/wiki/Repository_format/package/Manifest#Thin_Manifest for more info

**Pull request merged**
